[package]
name = "spin-amqp-sdk"
version.workspace = true
edition.workspace = true
include = ["../../spin-amqp.wit"]

[lib]
name = "spin_amqp_sdk"

[dependencies]
spin-executor = "3.0.1"
spin-amqp-macro = { path = "macro" }
wit-bindgen = { workspace = true }
