spin_manifest_version = 2

[application]
name = "amqp-rust"
version = "0.1.0"
description = "Demo app to receive AMQP messages."
authors = ["Justin Pflueger <justin.pflueger@fermyon.com>"]

[application.trigger.amqp]
address = "amqp://localhost:5672"
username = "user"
password = "password"

[[trigger.amqp]]
id = "trigger-msg-c01"
component = "msg-c01"
topic = "messages-in01"

[component.msg-c01]
source = "target/wasm32-wasi/release/amqp_rust.wasm"
allowed_outbound_hosts = ["amqp://localhost:5672"]

[component.msg-c01.build]
command = "cargo build --target wasm32-wasi --release"
